import { ImageResponse } from "next/og";

import { currentBuildRuntimeContext } from "@/config/installation-runtime";
import { hostRoutingForBuild } from "@/config/spoke-routing";

import { openGraphImageModelForContext } from "./opengraph-model";
import {
  OPEN_GRAPH_IMAGE_CONTENT_TYPE,
  OPEN_GRAPH_IMAGE_SIZE,
  openGraphImageElement,
} from "./opengraph-image-view";

export const size = OPEN_GRAPH_IMAGE_SIZE;
export const contentType = OPEN_GRAPH_IMAGE_CONTENT_TYPE;

interface OpengraphImageProps {
  readonly params: Promise<{ readonly site: string; readonly locale: string }>;
}

/**
 * Generates a branded social preview image at build time, for ONE site + ONE locale.
 *
 * M14 — THE BOUNDARY RULE: this route selects the current build's ONE Spoke context (the accepted one-Spoke
 * compatibility seam) and asks the PURE context-bound model for every Spoke-specific fact it draws — the
 * context's name, its localized tagline and its canonical origin. It keeps its static platform facts (size,
 * content type, visual style) and has no module-global `alt` (see `./opengraph-model` for why the framework
 * cannot express a context-dependent alt without changing this accepted URL).
 *
 * WHY THIS ROUTE LIVES OUTSIDE THE PAGE CATCH-ALL: Next.js requires a catch-all segment to be the
 * last segment that modifies the path, so a static metadata segment (`opengraph-image`) may not
 * sit under `[...segments]` — the framework refuses to build that tree at all. The image is
 * therefore generated by the SAME two dynamic segments a page URL carries (`/<site>/<locale>`),
 * which keeps the accepted URL (`/<site>/<locale>/opengraph-image`) and stays inside ONE site: an
 * unrecognized site or a locale that site does not serve deterministically falls back inside the CONTEXT's
 * own configuration, so a preview can never be labelled with another Spoke's identity.
 */
export default async function OpengraphImage({ params }: OpengraphImageProps) {
  const { site: siteCode, locale } = await params;

  // M16 — this PUBLIC compatibility boundary serves the ONE-Spoke runtime. A multi-Spoke Installation has no
  // single Spoke, so it refuses here rather than guessing: its images are rendered inside each Spoke's own
  // namespace (the internal route), where the request's host selected the context.
  if (hostRoutingForBuild().mode === "multi") {
    throw new Error(
      "FOUNDATION-MULTISITE-M16: this Installation declares SEVERAL Spokes, so no single Spoke owns the " +
        "public OpenGraph image. The image is rendered per host inside the hostname-selected Spoke's own " +
        "namespace; there is no default Spoke.",
    );
  }

  const model = openGraphImageModelForContext(currentBuildRuntimeContext(), siteCode, locale);

  return new ImageResponse(openGraphImageElement(model), size);
}
