import { ImageResponse } from "next/og";

import { runtimeContextForCurrentRequest } from "@/config/spoke-request";

import { openGraphImageModelForContext } from "./opengraph-model";
import {
  OPEN_GRAPH_IMAGE_CONTENT_TYPE,
  OPEN_GRAPH_IMAGE_SIZE,
  openGraphImageElement,
} from "./opengraph-image-view";

export const size = OPEN_GRAPH_IMAGE_SIZE;
export const contentType = OPEN_GRAPH_IMAGE_CONTENT_TYPE;

interface OpengraphImageProps {
  readonly params: Promise<{ readonly site: string; readonly locale: string }>;
}

/**
 * Generates a branded social preview image, for ONE site + ONE locale, of ONE request-selected Spoke.
 *
 * WHICH SPOKE (M17). The Spoke is the one THIS REQUEST selected: the request boundary matched the exact
 * hostname claim and carried its runtime segment on a private upstream header, and
 * `runtimeContextForCurrentRequest` resolves that segment to an explicit context — or returns nothing, in
 * which case this route REFUSES. The Spoke is deliberately NOT encoded in the OpenGraph route pathname (the
 * accepted public URL stays `/＜site＞/＜locale＞/opengraph-image`), and no default or first Spoke may stand in:
 * a preview must never be labelled with a Spoke whose host did not ask for it.
 *
 * The route still keeps its static platform facts (size, content type, visual style) and still asks the PURE
 * context-bound model for every Spoke-specific fact it draws — the context's name, its localized tagline and
 * its canonical origin (see `./opengraph-model` for why the framework cannot express a context-dependent
 * `alt` without changing this accepted URL).
 *
 * WHY THIS ROUTE LIVES OUTSIDE THE PAGE CATCH-ALL: Next.js requires a catch-all segment to be the
 * last segment that modifies the path, so a static metadata segment (`opengraph-image`) may not
 * sit under `[...segments]` — the framework refuses to build that tree at all. The image is
 * therefore generated by the SAME two dynamic segments a page URL carries (`/<site>/<locale>`).
 */
export default async function OpengraphImage({ params }: OpengraphImageProps) {
  const { site: siteCode, locale } = await params;

  const context = await runtimeContextForCurrentRequest();
  if (context === null) {
    throw new Error(
      "FOUNDATION-MULTISITE-M17: no Spoke answers this request, so no public OpenGraph image can be drawn. " +
        "The image belongs to the hostname-selected Spoke, and there is no default Spoke.",
    );
  }

  const model = openGraphImageModelForContext(context, siteCode, locale);

  return new ImageResponse(openGraphImageElement(model), size);
}

