import { ImageResponse } from "next/og";

import { currentBuildRuntimeContext } from "@/config/installation-runtime";
import { openGraphImageModelForContext } from "./opengraph-model";

export const size = {
  width: 1200,
  height: 630,
};
export const contentType = "image/png";

interface OpengraphImageProps {
  readonly params: Promise<{ readonly site: string; readonly locale: string }>;
}

/**
 * Generates a branded social preview image at build time, for ONE site + ONE locale.
 *
 * M14 — THE BOUNDARY RULE: this route selects the current build's ONE Spoke context (the accepted one-Spoke
 * compatibility seam) and asks the PURE context-bound model for every Spoke-specific fact it draws — the
 * context's name, its localized tagline and its canonical origin. It keeps its static platform facts (size,
 * content type, visual style) and has no module-global `alt` (see `./opengraph-model` for why the framework
 * cannot express a context-dependent alt without changing this accepted URL).
 *
 * WHY THIS ROUTE LIVES OUTSIDE THE PAGE CATCH-ALL: Next.js requires a catch-all segment to be the
 * last segment that modifies the path, so a static metadata segment (`opengraph-image`) may not
 * sit under `[...segments]` — the framework refuses to build that tree at all. The image is
 * therefore generated by the SAME two dynamic segments a page URL carries (`/<site>/<locale>`),
 * which keeps the accepted URL (`/<site>/<locale>/opengraph-image`) and stays inside ONE site: an
 * unrecognized site or a locale that site does not serve deterministically falls back inside the CONTEXT's
 * own configuration, so a preview can never be labelled with another Spoke's identity.
 */
export default async function OpengraphImage({ params }: OpengraphImageProps) {
  const { site: siteCode, locale } = await params;
  const model = openGraphImageModelForContext(currentBuildRuntimeContext(), siteCode, locale);

  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          background: "linear-gradient(135deg, #0a0a0a 0%, #1e3a8a 100%)",
          padding: "80px",
          color: "#ededed",
          fontFamily: "sans-serif",
        }}
      >
        <div
          style={{
            display: "flex",
            fontSize: 28,
            letterSpacing: 8,
            textTransform: "uppercase",
            color: "#60a5fa",
          }}
        >
          {model.siteName}
        </div>

        <div
          style={{
            display: "flex",
            fontSize: 64,
            fontWeight: 700,
            lineHeight: 1.15,
            maxWidth: 940,
          }}
        >
          {model.tagline}
        </div>

        <div style={{ display: "flex", fontSize: 26, color: "#a3a3a3" }}>{model.imageUrl}</div>
      </div>
    ),
    size,
  );
}
