import type { Metadata, Viewport } from "next";
import { Geist_Mono, Plus_Jakarta_Sans } from "next/font/google";

import { layoutForContext, layoutMetadataForContext, spokeServerComposition } from "@/app/[...segments]/server-composition";

import { spokePublicDestination } from "./spoke-request-context";
import "../../globals.css";

/**
 * THE INTERNAL SPOKE ROUTE — the ONE renderer of a hostname-selected Spoke (FOUNDATION-MULTISITE-M16)
 * ====================================================================================================
 *
 * `/~spoke/<runtime-segment>/<public path>` is how the request boundary hands a request to the Spoke the
 * HOST selected. This route is the ONLY thing that reads the runtime segment, and it reads it for ONE
 * purpose:
 *
 *     runtimeContextForSegment(segment)   the explicit, immutable context of that Spoke — nothing else
 *
 * There is NO second renderer here. The page and its metadata are composed by the SAME shared server
 * composition the public route uses (`@/app/[...segments]/server-composition`), from the context this route
 * selected — so multi-Spoke operation and one-Spoke operation render through exactly one composition, and a
 * second context cannot share chrome with the first.
 *
 * WHY THE PREFIX IS INTERNAL. The rewrite is performed by the request boundary, and a DIRECT external
 * request to `/~spoke/**` is refused there — this layout additionally requires the rewrite's own marker
 * header, so a request that somehow reached the route without being rewritten renders NOTHING. And because
 * every URL the composition emits is composed from the PUBLIC path handed to it below, the prefix can never
 * appear in a link, a canonical, an alternate, an OpenGraph value, a sitemap or a redirect.
 *
 * STATIC PLATFORM FACTS stay here (typography, the stylesheet, the mobile chrome colors): they are facts
 * about this deployment's platform, never about a request.
 */
const brandSans = Plus_Jakarta_Sans({
  variable: "--font-brand-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const HTML_CLASS_NAME = `${brandSans.variable} ${geistMono.variable} h-full antialiased`;

/**
 * A PUBLIC path may arrive incomplete (a bare Site, or no Site at all): completion is decided INSIDE the
 * selected Spoke — by the code below, from that Spoke's own resolved Sites — and it is answered with a PUBLIC
 * redirect (307), never with a different Spoke and never with the internal prefix.
 *
 * `dynamicParams` therefore stays permissive: the paths that must be COMPLETED cannot be prerendered, while
 * every discovered (site, locale, route) is still generated by `generateStaticParams` below.
 */
export const dynamicParams = true;

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#0a0a0a" },
  ],
};

interface SpokeLayoutProps {
  readonly children: React.ReactNode;
  readonly params: Promise<{ readonly segment: string; readonly segments?: string[] }>;
}

export async function generateMetadata({ params }: SpokeLayoutProps): Promise<Metadata> {
  const { segment, segments } = await params;
  const { context, destination } = await spokePublicDestination(segment, segments ?? []);
  return layoutMetadataForContext(
    spokeServerComposition(context),
    destination.segments as string[],
  );
}

export default async function SpokeLayout({ children, params }: SpokeLayoutProps) {
  const { segment, segments } = await params;
  const { context, destination } = await spokePublicDestination(segment, segments ?? []);

  return layoutForContext(
    spokeServerComposition(context),
    destination.segments as string[],
    children,
    HTML_CLASS_NAME,
  );
}
